version: '2.2'
services:
  resolver:
    image: "jodydadescott/home-openhab:latest"
    container_name: openhab
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/flash/persist/container_data/openhab/conf:/openhab/conf"
      - "/mnt/flash/persist/container_data/openhab/userdata:/openhab/userdata"
    environment:
      ADTPULSE_USER: "myuser"
      ADTPULSE_PASSWORD: "mypassword"
      OPENHAB_HTTP_PORT: "7080"
      OPENHAB_HTTPS_PORT: "7443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=America/Chicago"
