#!/bin/sh

UPDATE_INTERVAL_DEFAULT=3600
TTL_DEFAULT=600

cd $(dirname $0)
[ -f lib.dynamicdns ] || {  echo "lib.dynamicdns not found" 1>&2; exit 2; }
. lib.dynamicdns

main() {
  [[ $UPDATE_INTERVAL ]] || {
    UPDATE_INTERVAL=$UPDATE_INTERVAL_DEFAULT
    err "UPDATE_INTERVAL set to $UPDATE_INTERVAL from default"
  } 

  run=1
  trap run=0 SIGINT SIGTERM
  err "Running job on start"
  update_arecord ||:
  local counter=$UPDATE_INTERVAL
  while [ true ]; do
    [ $run -eq 1 ] || break
    let counter=counter-1
    [ $counter -le 0 ] && {
      counter=$UPDATE_INTERVAL
      err "Running updated on interval"
      update_arecord ||:
    }
    sleep 1
  done
  err "Goodbye"
}

main $@
