version: '2.2'
services:
  asterisk:
    image: "jodydadescott/home-asterisk:latest"
    container_name: asterisk
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/flash/persist/container_data/asterisk/conf:/etc/asterisk"
      - "/mnt/flash/persist/container_data/asterisk/db:/var/log/asterisk"
